version: '3'
services:
  master_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minesweeper_db
    ports:
      - '5432:5432'
  master_redis:
    image: redis:latest
    ports:
      - '6379:6379'