version: '3'
services:
  master_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  master_redis:
    image: redis:latest
    ports:
      - '6379:6379'